# Generated by Django 5.0.2 on 2024-03-25 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('serv', '0001_initial'), ('serv', '0002_rename_played_at_game_requested_at_game_completed_at_and_more'), ('serv', '0003_remove_game_gamemaster_game_moves_and_more'), ('serv', '0004_remove_score_proposing_team_alter_game_player_and_more'), ('serv', '0005_rename_stage_id_stage_name'), ('serv', '0006_rename_name_stage_endpoint'), ('serv', '0007_alter_stage_endpoint'), ('serv', '0008_team')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_data', models.TextField()),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=100, unique=True)),
                ('time_limit', models.IntegerField(blank=True, default=None, help_text='Time limit in seconds', null=True)),
                ('running', models.BooleanField(default=False)),
                ('maps', models.ManyToManyField(to='serv.map')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serv.map')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
                ('completed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('moves', models.TextField(default='')),
                ('reference_score', models.IntegerField(blank=True, null=True)),
                ('stage', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='serv.stage')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serv.game')),
                ('referee', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
