# Generated by Django 5.0.2 on 2024-03-26 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serv', '0001_squashed_0008_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='reference_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
