# Generated by Django 5.0.3 on 2024-04-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serv", "0009_alter_game_reference_score_alter_score_referee"),
    ]

    operations = [
        #migrations.AddField(
        #    model_name="game",
        #    name="victory",
        #    field=models.BooleanField(default=False),
        #),
        #migrations.AddField(
        #    model_name="score",
        #    name="valid",
        #    field=models.BooleanField(default=False),
        #),
        migrations.AlterField(
            model_name="score",
            name="score",
            field=models.FloatField(),
        ),
    ]
