# Generated by Django 5.0.2 on 2024-03-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serv', '0009_alter_game_reference_score_alter_score_referee'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='victory',
            field=models.BooleanField(default=False),
        ),
    ]
