# Generated by Django 5.0.2 on 2024-03-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serv', '0010_game_victory'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
