# Generated by Django 5.0.2 on 2024-04-04 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serv', '0010_game_victory_score_valid_alter_score_score'),
        ('serv', '0011_score_valid'),
    ]

    operations = [
    ]
