# Generated by Django 5.0.2 on 2024-04-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serv', '0015_map_impossible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='impossible',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
