# Generated by Django 5.0.2 on 2024-04-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serv', '0018_game_analysis_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='end_of_moves_submission',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='end_of_score_submission',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
