# Generated by Django 5.0.2 on 2024-04-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serv', '0019_stage_end_of_moves_submission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='maps',
            field=models.ManyToManyField(blank=True, null=True, to='serv.map'),
        ),
    ]
